variables:
  FLUTTER_VERSION: 3.27.2
  BUNDLETOOL_VERSION: 1.18.0

include:
  - component: gitlab.com/dependabot-gitlab/dependabot-standalone/template@3.39.0
    inputs:
      gitlab_access_token: $dependabot_gitlab_access_token
      stage_name: scan
    rules:
      - if: $PACKAGE_MANAGER_SET

image: registry.gitlab.com/theonewiththebraid/flutter-dockerimages:$FLUTTER_VERSION-base

stages:
  - check
  - test
  - build
  - scan
  - deploy

.versioning-setup: &versioning-setup
  - export PUBSPEC_VERSION=$(cat pubspec.yaml | grep version | awk '{ print $2 }' | cut -f1 -d "+")
  - export POLYCULE_VERSION="$(git describe --always)"
  - export POLYCULE_IS_STABLE=$([ -n "$CI_COMMIT_TAG" ] && echo "true" || echo "false")
  - export FLUTTER_ARGS="$($POLYCULE_IS_STABLE || echo "--build-number $CI_PIPELINE_ID") --no-pub --dart-define=POLYCULE_IS_STABLE=$POLYCULE_IS_STABLE --dart-define=POLYCULE_VERSION=$POLYCULE_VERSION --dart-define=no_default_http_client=true --dart-define=cronetHttpNoPlay=true"

.flutter-setup: &flutter-setup
  - flutter pub get --enforce-lockfile
  - flutter gen-l10n

.keystore-setup: &keystore-setup
  - |
    [ -n "$KEY_BASE64" ] && cat "$KEY_BASE64" | base64 -d > android/app/keystore.jks || true

.reproducible-before: &reproducible-before
  - export BUILD_DIR="$(pwd)"
  - cd ..
  - mv "$BUILD_DIR" /tmp/build
  - pushd /tmp/build
  - export PUB_CACHE=$(pwd)/.pub-cache

.reproducible-after: &reproducible-after
  - popd
  - mv /tmp/build "$BUILD_DIR"
  - cd "$BUILD_DIR"

.signed: &signed
  only:
    - main
    - tags

.unsigned: &unsigned
  except:
    - schedules
    - tags
    - main

before_script:
  - *versioning-setup

.check:
  stage: check
  tags:
    - docker
  except:
    - schedules
    - tags
    - main
  before_script:
    - *flutter-setup

.test:
  stage: test
  tags:
    - docker
  except:
    - schedules
  before_script:
    - *flutter-setup

.build:
  stage: build
  before_script:
    - *versioning-setup
    - *flutter-setup
  except:
    - schedules

.deploy:
  stage: deploy
  before_script:
    - apk add git
    - *versioning-setup
  tags:
    - docker
  except:
    - schedules

.android:
  image: registry.gitlab.com/theonewiththebraid/flutter-dockerimages:$FLUTTER_VERSION-android
  extends: .build
  before_script:
    - *versioning-setup
    - *flutter-setup
    - *keystore-setup
  tags:
    - x86_64
    - docker

.bundletool:
  extends: .android
  before_script:
    - *versioning-setup
    - *keystore-setup
    - curl -L -O https://github.com/google/bundletool/releases/download/$BUNDLETOOL_VERSION/bundletool-all-$BUNDLETOOL_VERSION.jar
    - export BUNDLETOOL="java -jar $(pwd)/bundletool-all-$BUNDLETOOL_VERSION.jar"
  after_script:
    - *versioning-setup
    - unzip polycule-*.apks universal.apk
    - mv universal.apk polycule-$POLYCULE_VERSION.apk
  artifacts:
    paths:
      - polycule-*.apk

.linux:
  image: registry.gitlab.com/theonewiththebraid/flutter-dockerimages:$FLUTTER_VERSION-linux
  extends: .build
  before_script:
    - *versioning-setup
    - *flutter-setup

check:codestyle:
  extends: .check
  script:
    - dart analyze --fatal-infos
    - dart format lib test web --set-exit-if-changed
    - dart run import_sorter:main --exit-if-changed

check:podfile:
  extends: .check
  tags:
    - macos
    - nix-shell
  parallel:
    matrix:
      - PLATFORM: [ ios, macos ]
  script:
    - pushd $PLATFORM
    - cp Podfile.lock Podfile.lock.orig
    - pod install --deployment
    - pod update
    - diff -u Podfile.lock.orig Podfile.lock > Podfile.lock.diff
    - popd
  artifacts:
    paths:
      - Podfile.lock
      - Podfile.lock.orig
      - Podfile.lock.diff
    when: on_failure

check:podfile:commit:
  extends: .check
  dependencies:
    - check:podfile
  tags:
    - macos
    - nix-shell
  parallel:
    matrix:
      - PLATFORM: [ ios, macos ]
  when: manual
  script:
    - pushd $PLATFORM
    - pod update
    - git diff . > podfile.diff
    - git config --local user.name "< polycule > CI Pipeline"
    - git config --local user.email "gitlab@polycule.im"
    - git add Podfile Podfile.lock
    - git commit -sm chore\(deps\)\:\ update\ podfile\ \(manual\)
    - git push https://git:$CI_PUSH_TOKEN@gitlab.com/$CI_PROJECT_PATH.git HEAD:$CI_COMMIT_REF_NAME
    - popd
  artifacts:
    paths:
      - podfile.diff
    when: always

build:macos:debug:
  extends: .build
  script:
    - flutter build macos --debug $FLUTTER_ARGS
    - rm -rf polycule-$POLYCULE_VERSION-debug.app
    - mv build/macos/Build/Products/Debug/polycule.app polycule-$POLYCULE_VERSION-debug.app
    - cp /nix/store/*-olm-*/lib/libolm.3.dylib polycule-$POLYCULE_VERSION-debug.app/Contents/Frameworks
  <<: *unsigned
  tags:
    - macos
    - nix-shell
  allow_failure: true
  artifacts:
    paths:
      - polycule-*.app

build:macos:
  extends: .build
  script:
    - export HOME="/Users/$USER"
    - flutter build macos $FLUTTER_ARGS
    - rm -rf polycule-$POLYCULE_VERSION.app
    - mv build/macos/Build/Products/Release/polycule.app polycule-$POLYCULE_VERSION.app
    - cp /nix/store/*-olm-*/lib/libolm.3.dylib polycule-$POLYCULE_VERSION.app/Contents/Frameworks
  <<: *signed
  tags:
    - macos
    - nix-shell
    - privileged
  allow_failure: true
  artifacts:
    paths:
      - polycule-*.app

build:ios:debug:
  extends: .build
  script:
    - flutter build ipa --no-codesign --debug $FLUTTER_ARGS
    - rm -rf polycule-$POLYCULE_VERSION-debug.xcarchive || true
    - mv build/ios/archive/Runner.xcarchive polycule-$POLYCULE_VERSION-debug.xcarchive
  <<: *unsigned
  tags:
    - macos
    - nix-shell
  allow_failure: true
  artifacts:
    paths:
      - polycule-*.xcarchive
      - polycule-*.ipa

build:ipa:
  extends: .build
  script:
    - export HOME="/Users/$USER"
    - gem install --update xcodeproj
    - keychain initialize
    - app-store-connect fetch-signing-files $(xcode-project detect-bundle-id --project ios/*.xcodeproj) --platform IOS --type IOS_APP_STORE --create
    - keychain add-certificates
    - xcode-project use-profiles --export-options-plist=export_options.plist
    - flutter build ipa --export-options-plist=export_options.plist $FLUTTER_ARGS
    - app-store-connect publish --path build/ios/ipa/polycule.ipa
    - rm -rf polycule-$POLYCULE_VERSION.ipa || true
    - mv build/ios/ipa/polycule.ipa polycule-$POLYCULE_VERSION.ipa
  after_script:
    - keychain use-login
  <<: *signed
  tags:
    - macos
    - nix-shell
    - privileged
  allow_failure: true
  artifacts:
    paths:
      - polycule-*.ipa

build:bundle:unsigned:
  extends: .android
  script:
    - flutter build appbundle $FLUTTER_ARGS
    - mv build/app/outputs/bundle/release/app-release.aab polycule-$POLYCULE_VERSION-unsigned.aab
  <<: *unsigned
  artifacts:
    paths:
      - polycule-*.aab

build:bundle:
  extends: .android
  script:
    - flutter build appbundle $FLUTTER_ARGS
    - mv build/app/outputs/bundle/release/app-release.aab polycule-$POLYCULE_VERSION.aab
  <<: *signed
  artifacts:
    paths:
      - polycule-*.aab

build:apk:unsigned:
  extends: .bundletool
  needs:
    - build:bundle:unsigned
  script:
    - $BUNDLETOOL build-apks --aapt2="$(which aapt2)" --mode=universal --bundle=polycule-$POLYCULE_VERSION-unsigned.aab --output=polycule-$POLYCULE_VERSION-unsigned.apks
  <<: *unsigned

scan:fdroid:
  needs:
    - build:apk:unsigned
  stage: scan
  before_script:
    - *versioning-setup
    - apt update && apt install -y -qq --no-install-recommends fdroidserver dexdump
  script:
    - mv polycule-$POLYCULE_VERSION.apk polycule-unsigned.apk
    - fdroid scanner -v -e polycule-unsigned.apk
  <<: *unsigned
  tags:
    - x86_64
    - docker

build:apk:
  extends: .bundletool
  needs:
    - build:bundle
  script:
    - $BUNDLETOOL build-apks --aapt2="$(which aapt2)" --ks="android/app/keystore.jks" --ks-pass=file:"${KEYSTORE_PASS_FILE}" --ks-key-alias="${KEYSTORE_ALIAS}" --key-pass=file:"${KEYSTORE_KEY_FILE}" --mode=universal --bundle=polycule-$POLYCULE_VERSION.aab --output=polycule-$POLYCULE_VERSION.apks
  <<: *signed
  except:
    - schedules
    - tags

build:apk:tag:
  extends: .android
  before_script:
    - *versioning-setup
    - *keystore-setup
  script:
    - *reproducible-before
    - *flutter-setup
    - sed -i -e '1a add_link_options("LINKER:--build-id=none")' $PUB_CACHE/hosted/pub.dev/{flutter_zxing,flutter_olm}-*/*/CMakeLists.txt
    - flutter build apk $FLUTTER_ARGS --release --split-per-abi
    - |
      for abi in "armeabi-v7a" "arm64-v8a" "x86_64"; do
        zipalign -p 4 build/app/outputs/flutter-apk/app-$abi-release.apk polycule-$abi-$POLYCULE_VERSION.apk
        apksigner sign --ks="android/app/keystore.jks" --ks-pass=file:"${KEYSTORE_PASS_FILE}" --ks-key-alias="${KEYSTORE_ALIAS}" --key-pass=file:"${KEYSTORE_KEY_FILE}" polycule-$abi-$POLYCULE_VERSION.apk
      done
    - *reproducible-after
  artifacts:
    paths:
      - polycule-*.apk
  only:
    - tags

build:web:
  image: registry.gitlab.com/theonewiththebraid/flutter-dockerimages:$FLUTTER_VERSION-web
  extends: .build
  script:
    - ./scripts/download-olm.sh
    - dart compile js web/web_worker.dart -m -o web/web_worker.dart.js
    - flutter build web --native-null-assertions --no-web-resources-cdn --base-href "/web/" --source-maps $FLUTTER_ARGS --dart-define=no_default_http_client=false
    - rm -rf polycule-web-$POLYCULE_VERSION
    - mv build/web polycule-web-$POLYCULE_VERSION
  artifacts:
    paths:
      - polycule-web-*

build:linux:x86_64:
  extends: .linux
  script:
    - flutter build linux $FLUTTER_ARGS
    - rm -rf polycule-$POLYCULE_VERSION-amd64
    - mv ./build/linux/x64/release/bundle polycule-$POLYCULE_VERSION-amd64
  tags:
    - x86_64
    - docker
  artifacts:
    paths:
      - polycule-*-amd64

build:linux:aarch64:
  extends: .linux
  script:
    - flutter build linux $FLUTTER_ARGS
    - rm -rf polycule-$POLYCULE_VERSION-aarch64
    - mv ./build/linux/arm64/release/bundle polycule-$POLYCULE_VERSION-aarch64
  tags:
    - aarch64
    - docker
  artifacts:
    paths:
      - polycule-*-aarch64

build:fedora:aarch64:
  extends: build:linux:aarch64
  image: fedora
  before_script:
    # Flutter tool dependencies
    - dnf install -y curl git unzip which xz zip
    # Flutter test dependencies
    - dnf install -y mesa-libGLU
    # Flutter desktop dependencies
    - dnf install -y clang cmake git ninja-build pkg-config gtk3-devel xz-devel libstdc++-devel
    # < polycule > development dependencies
    - dnf install -y openssl-devel libsecret-devel mimalloc-devel mpv-devel
    # < polycule > runtime dependencies
    - dnf install -y xdg-user-dirs dbus mpv mimalloc libnotify libolm
    - curl -O https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-linux-arm64-release.zip && unzip dartsdk-linux-arm64-release.zip && rm -f dartsdk-linux-arm64-release.zip
    - export PATH="$PATH":"$HOME/.pub-cache/bin:$(pwd)/.fvm/flutter_sdk/bin:$(pwd)/dart-sdk/bin"
    - dart --disable-analytics
    - dart pub global activate fvm
    - fvm use --skip-pub-get -f $FLUTTER_VERSION
    - flutter --disable-analytics
    - *versioning-setup
    - *flutter-setup

build:debian:x86_64:
  image: registry.gitlab.com/theonewiththebraid/flutter-dockerimages:$FLUTTER_VERSION-debian
  extends: .linux
  script:
    - sed -i "s/DATE/$(date -R)/g" debian/changelog
    - sed -i "s/VERSION/$PUBSPEC_VERSION/g" debian/changelog

    - dpkg-buildpackage
    - mv ../polycule_*.deb .
  tags:
    - x86_64
    - docker
  artifacts:
    paths:
      - polycule_*.deb

build:debian:aarch64:
  image: registry.gitlab.com/theonewiththebraid/flutter-dockerimages:$FLUTTER_VERSION-debian
  extends: .linux
  script:
    - sed -i "s/DATE/$(date -R)/g" debian/changelog
    - sed -i "s/VERSION/$PUBSPEC_VERSION/g" debian/changelog
    - sed -i "s/x64/arm64/g" debian/polycule.install

    - dpkg-buildpackage
    - mv ../polycule_*.deb .
  tags:
    - aarch64
    - docker
  artifacts:
    paths:
      - polycule_*.deb

pages:
  extends: .deploy
  dependencies:
    - build:web
  image: alpine:latest
  script:
    - mkdir -p public/web
    - if [[ -n "$ASSETLINKS_JSON" && -f "$ASSETLINKS_JSON" ]]; then mkdir public/.well-known && cp "$ASSETLINKS_JSON" public/.well-known/assetlinks.json ; fi
    - cp -r polycule-web-$POLYCULE_VERSION/* public/web/
  artifacts:
    paths:
      - public
  only:
    - main
