variables:
  FLUTTER_VERSION: 3.29.2

include:
  - component: gitlab.com/dependabot-gitlab/dependabot-standalone/template@3.43.1
    inputs:
      gitlab_access_token: $dependabot_gitlab_access_token
      stage_name: scan
    rules:
      - if: $PACKAGE_MANAGER_SET

image: registry.gitlab.com/polycule_client/flutter-dockerimages:$FLUTTER_VERSION-base

stages:
  - check
  - test
  - build
  - scan
  - deploy

.versioning-setup: &versioning-setup
  - export PUBSPEC_VERSION=$(grep -m1 version pubspec.yaml | awk '{ print $2 }' | cut -f1 -d "+")
  - export POLYCULE_VERSION="$(git describe --always)"
  - export POLYCULE_IS_STABLE=$([ -n "$CI_COMMIT_TAG" ] && echo "true" || echo "false")
  - export FLUTTER_BASE_ARGS="--no-pub --dart-define=POLYCULE_IS_STABLE=$POLYCULE_IS_STABLE --dart-define=POLYCULE_VERSION=$POLYCULE_VERSION --dart-define=no_default_http_client=true --dart-define=cronetHttpNoPlay=true"
  - export FLUTTER_ARGS="$($POLYCULE_IS_STABLE || echo "--build-number $CI_PIPELINE_ID") ${FLUTTER_BASE_ARGS}"

.flutter-setup: &flutter-setup
  - |
    if [ "$(uname)" == "Darwin" ]; then source scripts/prepare-macos.sh; fi
  - export PUB_CACHE=$CI_PROJECT_DIR/.pub-cache
  - export CP_HOME_DIR=$CI_PROJECT_DIR/.pod-cache
  - flutter pub get --enforce-lockfile
  - flutter gen-l10n

.keystore-setup: &keystore-setup
  - |
    [ -n "$KEY_BASE64" ] && cat "$KEY_BASE64" | base64 -d > android/app/keystore.jks || true

.reproducible-before: &reproducible-before
  - export BUILD_DIR="$(pwd)"
  - cp -pr . /tmp/build
  - pushd /tmp/build
  - export PUB_CACHE=$(pwd)/.pub-cache

.reproducible-after: &reproducible-after
  - mkdir -p "$BUILD_DIR/build/app"
  - cp -pr /tmp/build/build/app/outputs "$BUILD_DIR/build/app/outputs"
  - popd

.signed: &signed
  only:
    - main
    - tags

.unsigned: &unsigned
  except:
    - schedules
    - tags
    - main

before_script:
  - *versioning-setup

.check:
  stage: check
  needs: [ ]
  except:
    - schedules
    - tags
    - main
  tags:
    - saas-linux-small-arm64
  before_script:
    - *flutter-setup

.test:
  stage: test
  needs: [ ]
  except:
    - schedules
  tags:
    - saas-linux-large-amd64
  before_script:
    - *flutter-setup

.build:
  stage: build
  needs: [ ]
  before_script:
    - *versioning-setup
    - *flutter-setup
  except:
    - schedules

.deploy:
  stage: deploy
  before_script:
    - apk add git
    - *versioning-setup
  tags:
    - saas-linux-small-arm64
  except:
    - schedules

.android:
  image: registry.gitlab.com/polycule_client/flutter-dockerimages:$FLUTTER_VERSION-android
  extends: .build
  before_script:
    - *versioning-setup
    - *flutter-setup
    - *keystore-setup
  tags:
    - saas-linux-xlarge-amd64

.bundletool:
  extends: .android
  before_script:
    - *versioning-setup
    - *keystore-setup
  after_script:
    - *versioning-setup
    - unzip polycule-*.apks universal.apk
    - mv universal.apk polycule-$PUBSPEC_VERSION.apk
  tags:
    - saas-linux-small-amd64
  artifacts:
    paths:
      - polycule-*.apk

.linux:
  image: registry.gitlab.com/polycule_client/flutter-dockerimages:$FLUTTER_VERSION-linux
  extends: .build
  before_script:
    - *versioning-setup
    - *flutter-setup

check:codestyle:
  extends: .check
  script:
    - dart analyze --fatal-infos
    - dart format . --set-exit-if-changed
    - dart run import_sorter:main --exit-if-changed

check:flutter_version:
  extends: .check
  script:
    - cp flutter_version flutter_version.orig
    - cp .gitlab-ci.yml .gitlab-ci.yml.orig
    - cp Dockerfile Dockerfile.orig
    - cp assets/matrix/sas-emoji.json assets/matrix/sas-emoji.json.orig
    - ./flutter_version.sh
    - ./scripts/download-sas-emoji-data.sh
    - diff -u flutter_version.orig flutter_version > flutter_version.diff
    - diff -u .gitlab-ci.yml.orig .gitlab-ci.yml > .gitlab-ci.yml.diff
    - diff -u Dockerfile.orig Dockerfile > Dockerfile.diff
    - diff -u assets/matrix/sas-emoji.json.orig assets/matrix/sas-emoji.json > sas-emoji.json.diff
  artifacts:
    paths:
      - flutter_version.diff
      - .gitlab-ci.yml.diff
      - Dockerfile.diff
      - sas-emoji.json.diff
    when: on_failure

check:flutter_version:commit:
  extends: .check
  when: manual
  before_script: [ ]
  script:
    - ./flutter_version.sh
    - ./scripts/download-sas-emoji-data.sh
    - git diff . > ../flutter_version.diff
    - git config --local user.name "< polycule > CI Pipeline"
    - git config --local user.email "gitlab@polycule.im"
    - git add flutter_version .gitlab-ci.yml Dockerfile assets/matrix/sas-emoji.json
    - git commit -sm chore\(deps\)\:\ update\ flutter_version\ \(manual\)
    - git push https://git:$CI_PUSH_TOKEN@gitlab.com/$CI_PROJECT_PATH.git HEAD:$CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - flutter_version.diff
    when: always

check:podfile:
  extends: .check
  # our macOS runners are faster
  tags:
    - macos
    - nix-shell
  script:
    - pushd ios
    - pod install --deployment
    - pod update
    - git diff . > Podfile.lock.diff
    - popd
    - pushd macos
    - pod install --deployment
    - pod update
    - git diff . > Podfile.lock.diff
    - popd
  artifacts:
    paths:
      - ios/Podfile.lock*
      - macos/Podfile.lock*
    when: on_failure

check:podfile:commit:
  extends: .check
  # our macOS runners are faster
  tags:
    - macos
    - nix-shell
  when: manual
  script:
    - pushd ios
    - pod update
    - git diff . > podfile.diff
    - git add Podfile Podfile.lock
    - popd
    - pushd macos
    - pod update
    - git diff . > podfile.diff
    - git add Podfile Podfile.lock
    - popd
    - git config --local user.name "< polycule > CI Pipeline"
    - git config --local user.email "gitlab@polycule.im"
    - git commit -sm chore\(deps\)\:\ update\ podfile\ \(manual\)
    - git push https://git:$CI_PUSH_TOKEN@gitlab.com/$CI_PROJECT_PATH.git HEAD:$CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - ios/podfile.diff
      - macos/podfile.diff
    when: always

# first build on a powerful machine
test:android:avd:prepare:
  stage: test
  extends: .android
  when: manual
  needs: [ ]
  script:
    - flutter build apk --profile --target-platform android-x64 -t integration_test/integration.dart $FLUTTER_BASE_ARGS
  <<: *unsigned
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-profile.apk

# then test on our KVM runner
.test:android:avd:
  stage: test
  extends: .android
  timeout: 10m
  needs:
    - test:android:avd:prepare
  parallel:
    matrix:
      - THEME_MODE: [ "dark", "light" ]
  services:
    - name: registry.gitlab.com/polycule_client/flutter-dockerimages:emulator-$EMULATOR_ANDROID_VERSION
      alias: emulator
    - name: matrixconduit/matrix-conduit:latest
      alias: homeserver
      variables:
        CONDUIT_SERVER_NAME: "homeserver"
        CONDUIT_PORT: 80
        CONDUIT_ADDRESS: "::"
        CONDUIT_DATABASE_BACKEND: "rocksdb"
        CONDUIT_DATABASE_PATH: "/rocksdb"
        CONDUIT_ALLOW_REGISTRATION: true
        CONDUIT_CONFIG: "/etc/conduit.toml"
  variables:
    HOMESERVER: "http://homeserver"
  script:
    - adb start-server
    - sleep 15
    - adb connect emulator:5555
    - scrcpy --no-audio --no-window -r recording.mkv &
    - ./scripts/emulator-android.sh
    # - dart integration_test/server/prepare_legacy.dart
    - flutter drive --profile --driver test_driver/integration_test.dart --target integration_test/integration.dart -d emulator:5555 --use-application-binary build/app/outputs/flutter-apk/app-profile.apk $FLUTTER_BASE_ARGS
  after_script:
    - pkill scrcpy || true
    - sleep 15
    - ffmpeg -i recording.mkv -c copy recording.mp4
    - zip screenshots-android-${FORMFACTOR}-${THEME_MODE}.zip $(git ls-files --modified --others --exclude-standard)
  <<: *unsigned
  tags:
    - x86_64
    - kvm
  artifacts:
    when: always
    paths:
      - recording.mp4
      - screenshots-*.zip

test:android:avd:phone:
  extends: .test:android:avd
  variables:
    FORMFACTOR: phone
    ANDROID_DEVICE: pixel_7_pro
    EMULATOR_ANDROID_VERSION: 35
    HOMESERVER: "http://homeserver"

test:android:avd:tablet:
  extends: .test:android:avd
  variables:
    FORMFACTOR: tablet
    ANDROID_DEVICE: pixel_c
    EMULATOR_ANDROID_VERSION: 27
    HOMESERVER: "http://homeserver"

test:android:avd:desktop:
  extends: .test:android:avd
  variables:
    FORMFACTOR: desktop
    ANDROID_DEVICE: desktop_small
    EMULATOR_ANDROID_VERSION: 35
    HOMESERVER: "http://homeserver"

.test:linux:
  stage: test
  extends: .linux
  needs: [ ]
  parallel:
    matrix:
      - COLOR_SCHEME: [ "prefer-dark", "prefer-light" ]
  variables:
    HOMESERVER: "http://conduit"
  services:
    - name: matrixconduit/matrix-conduit:latest
      alias: conduit
      variables:
        CONDUIT_SERVER_NAME: "conduit"
        CONDUIT_PORT: 80
        CONDUIT_DATABASE_BACKEND: "rocksdb"
        CONDUIT_DATABASE_PATH: "/rocksdb"
        CONDUIT_ALLOW_REGISTRATION: true
        CONDUIT_CONFIG: "/etc/conduit.toml"

  before_script:
    - apt update && apt install --no-install-recommends -y dbus-daemon gnome-keyring
  script:
    # gsettings set org.gnome.desktop.interface color-scheme $COLOR_SCHEME
    - |
      dbus-run-session bash -c " \
        echo "supersecret" | eval gnome-keyring-daemon --unlock && \
        dbus-update-activation-environment --all && \
        xvfb-run --auto-servernum -s -screen\ 0\ 1920x1080x8 \
        flutter drive --profile --driver test_driver/integration_test.dart --target integration_test/integration.dart \
        -d linux --dart-define=HOMESERVER=$HOMESERVER $FLUTTER_BASE_ARGS"
  tags:
    - saas-linux-medium-arm64
  artifacts:
    when: always
    paths:
      - assets/screenshots

test:screenshots:commit:
  stage: test
  needs:
    # - test:linux
    - test:android:avd:phone
    - test:android:avd:tablet
    - test:android:avd:desktop
  when: manual
  script:
    - |
      for file in screenshots-*.zip; do
        unzip $file
      done
    - git config --local user.name "< polycule > CI Pipeline"
    - git config --local user.email "gitlab@polycule.im"
    - git add assets/screenshots
    - git commit -sm feat\:\ update\ screenshots\ \(manual\)
    - git push https://git:$CI_PUSH_TOKEN@gitlab.com/$CI_PROJECT_PATH.git HEAD:$CI_COMMIT_REF_NAME
  <<: *unsigned

build:macos:debug:
  extends: .build
  image: macos-15-xcode-16
  tags:
    - saas-macos-medium-m1
  script:
    - flutter build macos --debug $FLUTTER_ARGS
    - rm -rf polycule-$POLYCULE_VERSION-debug.app
    - mv build/macos/Build/Products/Debug/polycule.app polycule-$POLYCULE_VERSION-debug.app
    - cp /usr/local/Cellar/libolm/*/lib/libolm.3.dylib polycule-$POLYCULE_VERSION-debug.app/Contents/Frameworks
  <<: *unsigned
  allow_failure: true
  artifacts:
    paths:
      - polycule-*.app

build:macos:
  extends: .build
  image: macos-15-xcode-16
  tags:
    - saas-macos-medium-m1
  script:
    - flutter build macos $FLUTTER_ARGS
    - rm -rf polycule-$POLYCULE_VERSION.app
    - mv build/macos/Build/Products/Release/polycule.app polycule-$POLYCULE_VERSION.app
    - cp /usr/local/Cellar/libolm/*/lib/libolm.3.dylib polycule-$POLYCULE_VERSION.app/Contents/Frameworks
  <<: *signed
  allow_failure: true
  artifacts:
    paths:
      - polycule-*.app

build:ios:debug:
  extends: .build
  image: macos-15-xcode-16
  tags:
    - saas-macos-medium-m1
  script:
    - flutter build ipa --no-codesign --debug $FLUTTER_ARGS
    - rm -rf polycule-$POLYCULE_VERSION-debug.xcarchive || true
    - mv build/ios/archive/Runner.xcarchive polycule-$POLYCULE_VERSION-debug.xcarchive
  <<: *unsigned
  allow_failure: true
  artifacts:
    paths:
      - polycule-*.xcarchive
      - polycule-*.ipa

build:ipa:
  extends: .build
  image: macos-15-xcode-16
  tags:
    - saas-macos-medium-m1
  script:
    - keychain initialize
    - app-store-connect fetch-signing-files $(xcode-project detect-bundle-id --project ios/*.xcodeproj) --platform IOS --type IOS_APP_STORE --create
    - keychain add-certificates
    - xcode-project use-profiles --export-options-plist=export_options.plist
    - flutter build ipa --export-options-plist=export_options.plist $FLUTTER_ARGS
    - app-store-connect publish --path build/ios/ipa/polycule.ipa
    - rm -rf polycule-$POLYCULE_VERSION.ipa || true
    - mv build/ios/ipa/polycule.ipa polycule-$POLYCULE_VERSION.ipa
  after_script:
    - keychain use-login
  <<: *signed
  allow_failure: true
  artifacts:
    paths:
      - polycule-*.ipa

build:bundle:unsigned:
  extends: .android
  script:
    - flutter build appbundle $FLUTTER_ARGS
    - mv build/app/outputs/bundle/release/app-release.aab polycule-$PUBSPEC_VERSION-unsigned.aab
  <<: *unsigned
  artifacts:
    paths:
      - polycule-*.aab

build:bundle:
  extends: .android
  script:
    - flutter build appbundle $FLUTTER_ARGS
    - mv build/app/outputs/bundle/release/app-release.aab polycule-$PUBSPEC_VERSION.aab
    - jarsigner -sigalg SHA256withRSA -digestalg SHA-256 -keystore "android/app/keystore.jks" -storepass "$(cat "$KEYSTORE_PASS_FILE")" -keypass "$(cat "$KEYSTORE_KEY_FILE")" polycule-$PUBSPEC_VERSION.aab "${KEYSTORE_ALIAS}"
  <<: *signed
  artifacts:
    paths:
      - polycule-*.aab

build:apk:unsigned:
  extends: .bundletool
  needs:
    - build:bundle:unsigned
  script:
    - bundletool build-apks --aapt2="$(which aapt2)" --mode=universal --bundle=polycule-$PUBSPEC_VERSION-unsigned.aab --output=polycule-$PUBSPEC_VERSION-unsigned.apks
  <<: *unsigned

scan:fdroid:
  needs:
    - build:apk:unsigned
  stage: scan
  before_script:
    - *versioning-setup
    - apt update && apt install -y -qq --no-install-recommends fdroidserver dexdump
  script:
    - fdroid scanner -v -e polycule-$PUBSPEC_VERSION.apk
  <<: *unsigned
  tags:
    - saas-linux-small-amd64

build:apk:
  extends: .bundletool
  needs:
    - build:bundle
  script:
    - bundletool build-apks --aapt2="$(which aapt2)" --ks="android/app/keystore.jks" --ks-pass=file:"${KEYSTORE_PASS_FILE}" --ks-key-alias="${KEYSTORE_ALIAS}" --key-pass=file:"${KEYSTORE_KEY_FILE}" --mode=universal --bundle=polycule-$PUBSPEC_VERSION.aab --output=polycule-$PUBSPEC_VERSION.apks
  <<: *signed
  except:
    - schedules
    - tags

build:apk:tag:
  extends: .android
  before_script:
    - *versioning-setup
    - *keystore-setup
  script:
    - *reproducible-before
    - *flutter-setup
    - sed -i -e '1a add_link_options("LINKER:--build-id=none")' $PUB_CACHE/hosted/pub.dev/{flutter_zxing,flutter_olm}-*/*/CMakeLists.txt
    - sed -i -e "1a add_compile_options(\"-ffile-prefix-map=$CI_PROJECT_DIR=/tmp/build\")" $PUB_CACHE/hosted/pub.dev/{flutter_zxing,flutter_olm}-*/*/CMakeLists.txt
    - flutter build apk $FLUTTER_ARGS --release --split-per-abi
    - *reproducible-after
    - |
      for abi in "armeabi-v7a" "arm64-v8a" "x86_64"; do
        zipalign -p 4 build/app/outputs/flutter-apk/app-$abi-release.apk polycule-$abi-$POLYCULE_VERSION.apk
        apksigner sign --ks="android/app/keystore.jks" --ks-pass=file:"${KEYSTORE_PASS_FILE}" --ks-key-alias="${KEYSTORE_ALIAS}" --key-pass=file:"${KEYSTORE_KEY_FILE}" polycule-$abi-$POLYCULE_VERSION.apk
      done
  artifacts:
    paths:
      - polycule-*.apk
  only:
    - tags

build:web:
  image: registry.gitlab.com/polycule_client/flutter-dockerimages:$FLUTTER_VERSION-web
  extends: .build
  script:
    - ./scripts/download-olm.sh
    - dart compile js web/web_worker.dart -m -o web/web_worker.dart.js
    - flutter build web --native-null-assertions --no-web-resources-cdn --base-href "/web/" --source-maps $FLUTTER_ARGS --dart-define=no_default_http_client=false
    - rm -rf polycule-web-$PUBSPEC_VERSION
    - mv build/web polycule-web-$PUBSPEC_VERSION
  artifacts:
    paths:
      - polycule-web-*

build:linux:x86_64:
  extends: .linux
  script:
    - flutter build linux $FLUTTER_ARGS
    - rm -rf polycule-$POLYCULE_VERSION-amd64
    - mv ./build/linux/x64/release/bundle polycule-$POLYCULE_VERSION-amd64
  tags:
    - saas-linux-medium-amd64
  artifacts:
    paths:
      - polycule-*-amd64

build:linux:aarch64:
  extends: .linux
  script:
    - flutter build linux $FLUTTER_ARGS
    - rm -rf polycule-$POLYCULE_VERSION-aarch64
    - mv ./build/linux/arm64/release/bundle polycule-$POLYCULE_VERSION-aarch64
  tags:
    - saas-linux-medium-arm64
  artifacts:
    paths:
      - polycule-*-aarch64

build:fedora:aarch64:
  extends: build:linux:aarch64
  image: fedora
  before_script:
    # Flutter tool dependencies
    - dnf install -y curl git unzip which xz zip
    # Flutter test dependencies
    - dnf install -y mesa-libGLU
    # Flutter desktop dependencies
    - dnf install -y clang cmake git ninja-build pkg-config gtk3-devel xz-devel libstdc++-devel
    # < polycule > development dependencies
    - dnf install -y openssl-devel libsecret-devel mimalloc-devel mpv-devel
    # < polycule > runtime dependencies
    - dnf install -y xdg-user-dirs dbus mpv mimalloc libnotify libolm
    - curl -O https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-linux-arm64-release.zip && unzip dartsdk-linux-arm64-release.zip && rm -f dartsdk-linux-arm64-release.zip
    - export PATH="$PATH":"$HOME/.pub-cache/bin:$(pwd)/.fvm/flutter_sdk/bin:$(pwd)/dart-sdk/bin"
    - dart --disable-analytics
    - dart pub global activate fvm
    - fvm use --skip-pub-get -f $FLUTTER_VERSION
    - flutter --disable-analytics
    - *versioning-setup
    - *flutter-setup

build:debian:x86_64:
  image: registry.gitlab.com/polycule_client/flutter-dockerimages:$FLUTTER_VERSION-debian
  extends: .linux
  script:
    - rm -R build
    - sed -i "s/DATE/$(date -R)/g" debian/changelog
    - sed -i "s/VERSION/$PUBSPEC_VERSION/g" debian/changelog

    - dpkg-buildpackage
    - mv ../polycule_*.deb .
  tags:
    - saas-linux-medium-amd64
  artifacts:
    paths:
      - polycule_*.deb

build:debian:aarch64:
  image: registry.gitlab.com/polycule_client/flutter-dockerimages:$FLUTTER_VERSION-debian
  extends: .linux
  script:
    - rm -R build
    - sed -i "s/DATE/$(date -R)/g" debian/changelog
    - sed -i "s/VERSION/$PUBSPEC_VERSION/g" debian/changelog
    - sed -i "s/x64/arm64/g" debian/polycule.install

    - dpkg-buildpackage
    - mv ../polycule_*.deb .
  tags:
    - saas-linux-medium-arm64
  artifacts:
    paths:
      - polycule_*.deb

pages:
  extends: .deploy
  needs:
    - build:web
  image: alpine:latest
  script:
    - mkdir -p public/web
    - if [[ -n "$ASSETLINKS_JSON" && -f "$ASSETLINKS_JSON" ]]; then mkdir public/.well-known && cp "$ASSETLINKS_JSON" public/.well-known/assetlinks.json ; fi
    - cp -r polycule-web-$PUBSPEC_VERSION/* public/web/
  artifacts:
    paths:
      - public
  only:
    - main
