name: polycule
description: "A simple and beautiful matrix client written in Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  animations: ^2.0.11
  dynamic_color: ^1.6.9
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  flutter_olm: ^1.4.1
  flutter_openssl_crypto: ^0.3.0
  flutter_secure_storage: ^9.0.0
  go_router: ^13.0.1
  html: ^0.15.4
  import_sorter: ^4.6.0
  intl: ^0.18.1
  matrix: ^0.25.5
  matrix_homeserver_recommendations: ^0.4.0
  olm: ^2.0.3
  path_provider: ^2.1.2
  provider: ^6.1.1
  sqflite_common_ffi: ^2.3.1
  sqlcipher_flutter_libs: ^0.6.0
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/logo/logo-circle.png
    - assets/icons/rosahaj/base/Rosahaj_Peek.png

  fonts:
    - family: Sono
      fonts:
        - asset: assets/fonts/sono.ttf

import_sorter:
  comments: false
  ignored_files:
    - \/lib\/l10n\/generated\/*

flutter_launcher_icons:
  # convert -background none -density 4096 -resize 1024x1024 assets/logo/logo-white.svg assets/logo/logo-white.png
  # convert -density 4096 -resize 1024x1024 assets/logo/logo-background.svg -alpha remove assets/logo/logo-background.png
  # convert -background none -density 4096 -resize 1024x1024 assets/logo/logo-circle.svg assets/logo/logo-circle.png
  image_path: "assets/logo/logo-circle.png"
  image_path_ios: "assets/logo/logo-background.png"

  adaptive_icon_foreground: "assets/logo/logo-white.png"
  adaptive_icon_background: "#3F51B5"

  android: true
  min_sdk_android: 16
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    background_color: "black"
    theme_color: "#3F51B5"
  windows:
    generate: true
    image_path: "assets/logo/logo-background.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/logo/logo-background.png"

dependency_overrides:
  matrix:
    git:
      url: https://github.com/TheOneWithTheBraid/matrix-dart-sdk
      ref: braid/sqflite-encryption-helper
