name: polycule
description: "A geeky and efficient [matrix] client for power users."
publish_to: 'none'

version: 0.0.9+9

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  animations: ^2.0.11
  app_links: ^6.3.2
  async: ^2.11.0
  barcode_widget: ^2.0.4
  blurhash_dart: ^1.2.1
  collection: ^1.19.1
  cross_file: ^0.3.4+1
  # required for native iOS icons
  cupertino_http: ^2.0.1
  cupertino_icons: ^1.0.8
  dart_animated_emoji: ^0.0.3
  diacritic: ^0.1.6
  diffutil_dart: ^4.0.1
  dynamic_color: ^1.6.9
  emoji_extension: ^1.2.0
  fetch_client: ^1.1.2
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_confetti: ^0.3.4
  flutter_highlighting: ^0.9.0+11.8.0
  flutter_html: ^3.0.0-beta.2
  flutter_html_svg: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  flutter_keyboard_visibility: ^6.0.0
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_olm: ^2.0.0
  flutter_openssl_crypto: ^0.5.0
  flutter_secure_storage: ^9.2.3
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.2.0
  flutter_zxing: ^1.8.2
  go_router: ^14.3.0
  highlighting: ^0.9.0+11.8.0
  html: ^0.15.4
  http: ^1.2.2
  image: ^4.5.2
  image_picker: ^1.1.2
  import_sorter: ^4.6.0
  intl: ">=0.18.0 <2.0.0"
  just_audio: ^0.9.41
  just_audio_media_kit: ^2.0.5
  just_waveform: ^0.0.5
  linkify: ^5.0.0
  locale_names: ^1.1.1
  lottie: ^3.3.1
  matrix: ^0.35.0
  matrix_homeserver_recommendations: ^0.4.0
  media_kit: ^1.1.10+1
  media_kit_libs_video: ^1.0.5
  media_kit_video: ^1.2.5
  media_store_plus: ^0.1.3
  mime: ^2.0.0
  oidc: ^0.9.0
  olm: ^2.0.3
  path_provider: ^2.1.4
  provider: ^6.1.1
  receive_sharing_intent_plus: ^1.0.1
  sentry: ^8.12.0
  share_plus: ^10.1.0
  sqflite: ^2.4.0
  sqflite_common_ffi: ^2.3.4
  sqlcipher_flutter_libs: ^0.6.4
  unifiedpush: ^5.0.1
  unorm_dart: ^0.2.0
  url_launcher: ^6.2.6
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  collection: ">=0.19.0 <2.0.0"
  js: ">=0.7.0 <2.0.0"
  matrix:
    git:
      url: https://github.com/TheOneWithTheBraid/matrix-dart-sdk.git
      ref: braid/command-runner
  # https://github.com/media-kit/media-kit/issues/886
  media_kit:
    git:
      url: https://github.com/TheOneWithTheBraid/media-kit.git
      ref: braid/stub-template
      path: media_kit
  # https://github.com/media-kit/media-kit/issues/357
  media_kit_libs_linux:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: 4d8c634c28d439384aab40b9d2edff83077f37c9
      path: libs/linux/media_kit_libs_linux
  screen_brightness: ^2.0.0
  # https://github.com/UnifiedPush/flutter-connector/pull/155
  unifiedpush:
    git:
      url: https://github.com/TheOneWithTheBraid/flutter-connector.git
      ref: braid/flutter-cleanup
      path: unifiedpush

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/logo/logo-circle.png
    - assets/icons/matrix.svg
    - assets/icons/rosahaj/base/Rosahaj_Peek.png

  fonts:
    - family: Overpass Mono
      fonts:
        - asset: assets/fonts/overpassmono/OverpassMono-VariableFont.ttf
    - family: Noto Color Emoji
      fonts:
        - asset: assets/fonts/notocoloremoji/NotoColorEmoji-Regular.ttf
    - family: Noto Sans Mono
      fonts:
       - asset: assets/fonts/notosansmono/NotoSansMono-VariableFont.ttf
    - family: Marck Script
      fonts:
        - asset: assets/fonts/marckscript/MarckScript-Regular.ttf
    - family: Vollkorn
      fonts:
        - asset: assets/fonts/vollkorn/Vollkorn-VariableFont.ttf
        - asset: assets/fonts/vollkorn/Vollkorn-Italic-VariableFont.ttf
          style: italic
    - family: Inclusive Sans
      fonts:
        - asset: assets/fonts/inclusivesans/InclusiveSans-Regular.ttf
        - asset: assets/fonts/inclusivesans/InclusiveSans-Italic.ttf
          style: italic
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/opendyslexic3/OpenDyslexic3-Regular.ttf
        - asset: assets/fonts/opendyslexic3/OpenDyslexic3-Bold.ttf
          weight: 700
    # we do not want to contact Google Fonts
    #
    # We might encounter connections to Google Fonts. To prevent this, we can specify custom assets for the given fonts.
    #
    # keep in sync with : $FLUTTER_ROOT/bin/cache/flutter_web_sdk/lib/_engine/engine/font_fallback_data.dart
    #
    # Source : https://github.com/flutter/engine/blob/3.22.3/lib/web_ui/dev/roll_fallback_fonts.dart
    #
    # Currently, we do not need Noto fallback fonts since both Noto Mono and Noto Color Emoji are bundled
    #
    # Additional source for Noto Color Emoji Compat :
    # Source : https://mvnrepository.com/artifact/androidx.emoji/emoji-bundled/

    # Roboto fallback font
    #
    # Hard coded into engine
    # Source : https://github.com/flutter/engine/blob/3.22.3/lib/web_ui/lib/src/engine/canvaskit/fonts.dart#L16
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf

import_sorter:
  comments: false
  ignored_files:
    - \/lib\/l10n\/generated\/*

flutter_launcher_icons:
  # convert -background none -density 4096 -resize 1024x1024 assets/logo/logo-white.svg assets/logo/logo-white.png
  # convert -density 4096 -resize 1024x1024 assets/logo/logo-background.svg -alpha remove assets/logo/logo-background.png
  # convert -background none -density 4096 -resize 1024x1024 assets/logo/logo-circle.svg assets/logo/logo-circle.png
  image_path: "assets/logo/logo-circle.png"
  image_path_ios: "assets/logo/logo-background.png"

  adaptive_icon_foreground: "assets/logo/logo-white.png"
  adaptive_icon_background: "#3F51B5"
  adaptive_icon_monochrome: "assets/logo/logo-white.png"
  adaptive_icon_foreground_inset: 0

  android: true
  min_sdk_android: 16
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    background_color: "black"
    theme_color: "#3F51B5"
  windows:
    generate: true
    image_path: "assets/logo/logo-background.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/logo/logo-background.png"

