version: 2
updates:
  # https://github.com/dependabot/dependabot-core/issues/11489
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily
    versioning-strategy: increase
    allow:
      - dependency-type: all
  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: daily
  - package-ecosystem: swift
    directory: /macos
    schedule:
      interval: daily
  - package-ecosystem: swift
    directory: /ios
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
update-options:
  auto-merge: true
