build/linux/x64/release/bundle/polycule opt/polycule/
build/linux/x64/release/bundle/lib/ opt/polycule/
build/linux/x64/release/bundle/data/ opt/polycule/
linux/polycule usr/bin/
linux/business.braid.polycule.desktop usr/share/applications/
linux/business.braid.polycule.svg usr/share/pixmaps/
linux/business.braid.polycule.svg usr/share/icons/hicolor/scalable/apps/
linux/business.braid.polycule.metainfo.xml usr/share/metainfo/
