build/linux/x64/release/bundle/polycule opt/polycule/
build/linux/x64/release/bundle/lib/ opt/polycule/
build/linux/x64/release/bundle/data/ opt/polycule/
linux/polycule usr/bin/
linux/business.braid.polycule.desktop usr/share/applications/
assets/logo/logo-circle.svg usr/share/pixmaps/business.braid.polycule.svg
assets/logo/logo-circle.svg usr/share/icons/hicolor/scalable/apps/business.braid.polycule.svg
